[platformio]
default_envs = esp32dev

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit BME280 Library @ ^2.3.0
    adafruit/Adafruit Unified Sensor @ ^1.1.15
build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D OREGON_TX_BETA=1

[env:esp32dev]
board = esp32dev

[env:esp32c3]
board = esp32-c3-devkitm-1
build_flags =
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D TARGET_ESP32C3=1
